AIP 17 - Reactions to Messages
Adamant-im/AIPs pull request #51
Opened 2023-08-18 08:28 UTC by StanislavDevIOS

Discussion: https://github.com/Adamant-im/AIPs/issues/52 in Issues

2023-09-15 10:24 UTC, confleux approved these changes

2023-09-15 16:47 UTC, adamant-al approved these changes

2023-09-15 19:19 UTC, bludnic requested changes

2023-09-15 19:19 UTC, bludnic commented on AIPS/aip-17.md
> +  "reactto_id": "Transaction_ID",
I think it will be more clear to use same tx id as in the previous example

```suggestion
  "reactto_id": "7452709338464950789",
```

2023-09-16 16:39 UTC, just-software-dev approved these changes

2023-09-16 17:04 UTC, bludnic approved these changes

2023-09-16 17:07 UTC, merged