Accept AIPs 16 and 17
Adamant-im/AIPs pull request #53
Opened 2024-01-17 20:26 UTC by adamant-al

- Accept 16 and 17
- Grammar fixes

2024-01-17 23:36 UTC, bludnic approved these changes

2024-01-18 00:20 UTC, martiliones requested changes

2024-01-18 00:40 UTC, martiliones requested changes

2024-01-18 07:48 UTC, adamant-al commented on AIPS/aip-16.md
> +- Consider that the `replyto_id` message may not exist, or belongs th another sender, or is not decryptable
Forgot to tap "Push" :)

2024-01-18 07:51 UTC, martiliones approved these changes
🚀

2024-01-18 10:41 UTC, merged